import Fastify from 'fastify';
import Boom from '@hapi/boom';
import userRoutes from './routes/userRoutes.js';
import externalRoutes from './routes/externalRoutes.js';
import filterHooksPlugin from './hooks/filter.js';
import cassandraPlugin from './plugins/cassandra.js';

// Initialize Fastify with logging enabled
const fastify = Fastify({
  logger: true
});

// --- GLOBAL ERROR HANDLER ---
// This intercepts every error thrown inside a Fastify route or preHandler
fastify.setErrorHandler((error, request, reply) => {
  // If the error was generated by Boom (e.g. throw Boom.notFound())
  if (error.isBoom) {
    // Boom automatically formats the payload and sets the correct HTTP status code
    reply.status(error.output.statusCode).send(error.output.payload);
  } else {
    // If it's a standard Fastify validation error, or an unexpected crash (500), pass it through
    reply.send(error);
  }
});

// --- REGISTER PLUGINS ---
// 1. Register our Cassandra connection pool globally
fastify.register(cassandraPlugin);

// 2. Register our global onRequest IP filters and Auth preHandlers
fastify.register(filterHooksPlugin);


// --- REGISTER ROUTES ---
// We prefix all routes inside this plugin with /api/users
fastify.register(userRoutes, { prefix: '/api/users' });

// We prefix our external Cassandra and Upstream HTTP examples with /api/external
fastify.register(externalRoutes, { prefix: '/api/external' });


// Start the server (using modern async/await initialization pattern)
const startServer = async () => {
  try {
    await fastify.listen({ port: 3000, host: '0.0.0.0' });
    console.log('\n--- Fastify is Running! ---');
    console.log('Try querying the Cassandra cluster (It will fail gracefully with a Boom 503 since no cluster is running locally):');
    console.log('curl -H "Authorization: Bearer secret-token" http://localhost:3000/api/external/cassandra/1');
    console.log('\nTry missing the Authorization header (It will fail with a Boom 401):');
    console.log('curl http://localhost:3000/api/external/cassandra/1');
    console.log('\nTry querying an unreachable upstream HTTP API (It will fail gracefully with a Boom 503):');
    console.log('curl -X POST -H "Content-Type: application/json" -d \'{"targetUrl": "http://localhost:9999"}\' http://localhost:3000/api/external/upstream');
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

startServer();
