import Fastify from 'fastify';
import Boom from '@hapi/boom';
import userRoutes from './routes/userRoutes.js';

// Initialize Fastify with logging enabled
const fastify = Fastify({
  logger: true
});

// --- GLOBAL ERROR HANDLER ---
// This intercepts every error thrown inside a Fastify route or preHandler
fastify.setErrorHandler((error, request, reply) => {
  // Log the error internally
  request.log.error(error);

  // If the error was generated by Boom (e.g. throw Boom.notFound())
  if (error.isBoom) {
    // Boom automatically formats the payload and sets the correct HTTP status code
    reply.status(error.output.statusCode).send(error.output.payload);
  } else {
    // If it's a standard Fastify validation error, or an unexpected crash (500), pass it through
    reply.send(error);
  }
});


// A simple health check route (Shorthand Declaration)
fastify.get('/api/health', async (request, reply) => {
  // Fastify automatically sends this as JSON with a 200 status code
  return { status: 'UP' };
});

// Register the user routes plugin
// We prefix all routes inside this plugin with /api/users
fastify.register(userRoutes, { prefix: '/api/users' });


// Start the server (using modern async/await initialization pattern)
const startServer = async () => {
  try {
    await fastify.listen({ port: 3000, host: '0.0.0.0' });
    console.log('\n--- Fastify is Running! ---');
    console.log('Try querying:');
    console.log('curl http://localhost:3000/api/users');
    console.log('curl http://localhost:3000/api/users/999  <-- THIS WILL RETURN A BOOM 404 NOT FOUND');
    console.log('curl -X POST -H "Content-Type: application/json" -d \'{"name": "Charlie"}\' http://localhost:3000/api/users   <-- THIS WILL FAIL SCHEMA VALIDATION');
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

startServer();
